server:
  port: ${port:8761}

spring:
  application:
    name: spring-eureka-server 
    

eureka:
  client:
    register-with-eureka: false
      
logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
  path: logs/${spring.application.name}_${random.value}
