logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
  path: logs/${spring.application.name}_${server.port}
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eurekaServerName:localhost}:${eurekaServerPort:80}/eureka/
  
management.security.enabled: false