eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    instanceId: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://${eurekaServerName:localhost}:${eurekaServerPort:80}/eureka/
      
logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
  path: logs/${spring.application.name}_${server.port}
  
      
zuul.url: http://${zuulServerName:localhost}:${zuulServerPort:80}/

management.security.enabled: false